### ISSUE TITLE
Tests not running because of missing 'bootstrap' directive in 'phpunit.xml.dist'  

### ISSUE THREAD

**Issue by MassiAtZend** [zfcampus/zf-apigility-skeleton#145]
Running tests in a freshly cloned directory generates the following error:
Fatal error: Class 'Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase' not found in ../api-skel/module/Application/test/Controller/IndexControllerTest.php on line 13

The error is due to the fact the 'composer' autoloading logic is not included in the testing execution.

A simple fix is to add 'bootstrap="./vendor/autoload.php"' in 'phpunit.xml.dist' file.

**Comment by alextech** [comment]
Bigger reason is lack of `zend-test` dependency in `require-dev`.

However, after installing, test still do not run complaining about some missing configuration cache. file_put_contents(data/cache/module-classmap-cache.application.module.cache.php): failed to open stream: No such file or directory

I am familiar with MVC skeleton, not fully understanding Apigility though to be able to fix both problems one time so, @weierophinney can you please give a hint, how/why configuration caching would interfere with unit test execution?

**Comment by alextech** [comment]
Never mind, missing file_put_contents is a fault in my setup.

**Comment by weierophinney** [comment]
Thanks, @alextech; will release with 1.5.0.

**Comment by worthwhileindustries** [comment]
@alextech can you elaborate on what the fix for this problem was?

"However, after installing, test still do not run complaining about some missing configuration cache. file_put_contents(data/cache/module-classmap-cache.application.module.cache.php): failed to open stream: No such file or directory"

"Never mind, missing file_put_contents is a fault in my setup."
